Bucket[0]
485,hammer,thermometer,compact-disc,bathroom
819,album,army,slave,cup
940,chess-board,web,bird,zoo
321,shop,library,prison,desk
Bucket[1]
219,shop,library,prison,desk
314,sandpaper,slave,television,shoes
346,tapestry,toilet,pin,junk
466,ears,air,sandpaper,sun
473,compact-disc,robot,weapon,map
701,key,slave,prison,air
789,cappuccino,film,gemstone,tunnel
174,tapestry,kaleidoscope,liquid,liquid
288,microscope,computer,junk,signature
Bucket[2]
71,spoon,database,backpack,gloves
141,circle,money,prison,vacuum
212,crystal,air,finger,gemstone
242,planet,banana,gas,yawn
396,water,meteor,finger,dingbat
821,drink,book,vacuum,book
904,spectrum,bee,butterfly,liquid
924,eraser,paintbrush,necklace,printer
71,spoon,database,backpack,gloves
100,spoon,database,backpack,gloves
344,planet,banana,gas,yawn
Bucket[3]
17,drink,thermometer,sandpaper,army
188,barbecue,bathtub,spotlight,salt
504,hieroglyph,salt,oodle,microscope
568,chair,torpedo,prison,fire
763,electricity,film,treadmill,library
776,airport,tongue,gas,shoes
837,compass,kaleidoscope,shoes,telescope
17,drink,thermometer,sandpaper,army
46,drink,thermometer,sandpaper,army
17,drink,thermometer,sandpaper,army
243,circle,money,prison,vacuum
314,crystal,air,finger,gemstone
Bucket[4]
79,pin,airforce,bottle,leg
165,money,maze,clown,database
648,bowl,hot,army,treadmill
657,vacuum,pebble,printer,chess-board
851,printer,bed,guitar,tennis
971,box,adult,bird,apple
79,pin,airforce,bottle,leg
297,money,sword,backpack,tennis
Bucket[5]
35,box,triangle,sun,apple
361,thermometer,coffee,signature,salt
537,pendulum,planet,garden,gemstone
35,box,triangle,sun,apple
108,pin,airforce,bottle,leg
181,pin,airforce,bottle,leg
267,money,maze,clown,database
357,girl,staircase,robot,highway
Bucket[6]
31,water,diamond,pendulum,sun
416,mum,ice,highway,videotape
490,rib,mouth,clown,junk
639,circus,baby,worm,bathroom
697,feather,electricity,meteor,guitar
973,bed,x-ray,garden,bowl
31,water,diamond,pendulum,sun
116,diamond,gate,meat,fruit
133,water,diamond,pendulum,sun
307,chair,shower,ring,thermometer
Ovflow->
Bucket[7]
Ovflow->
Bucket[8]
619,paintbrush,telescope,pith,air
927,child,alphabet,record,treadmill
262,sandpaper,junk,insect,cup
393,clown,leg,leather,robot
Bucket[9]
149,compact-disc,necklace,eyes,meteor
529,cave,bottle,baby,treadmill
592,tapestry,bird,pepper,television
982,robot,pendulum,floodlight,typewriter
149,school,printer,button,sandpaper
371,alphabet,skeleton,balloon,desk
Bucket[10]
78,floodlight,fruit,rocket,hammer
235,bed,salt,rifle,printer
342,radar,bottle,planet,bathroom
380,rib,fruit,planet,sun
643,planet,bathroom,rib,vacuum
750,rock,torpedo,vulture,leg
762,swim,gloves,eyes,shoes
804,balloon,gemstone,airport,bathroom
984,jet-fighter,telescope,triangle,salt
994,hose,yawn,tiger,desk
78,floodlight,fruit,rocket,hammer
82,diamond,ears,rib,worm
338,diamond,chisel,explosive,dingbat
Ovflow->
Bucket[11]
435,rock,pin,earth,solid
459,milkshake,dingbat,carpet,computer
603,man,finger,hat,television
826,hose,microscope,monster,junk
886,ship,elephant,explosive,necklace
960,bed,gemstone,needle,backpack
155,diamond,ears,rib,worm
Bucket[12]
8,compact-disc,chair,rocket,gas
152,pin,potato,chief,prison
344,surveyor,foot,x-ray,cappuccino
393,ears,space,win,tongue
397,alphabet,maze,sword,sunglasses
471,microscope,carpet,electricity,signature
616,paintbrush,post,famine,sunglasses
698,family,torch,staircase,passport
703,child,record,zebra,television
731,paintbrush,coffee-shop,plane,cup
786,compact-disc,mosquito,teeth,compact-disc
842,box,clock,tiger,vacuum
890,printer,rifle,pebble,bird
8,compact-disc,chair,rocket,gas
37,compact-disc,chair,rocket,gas
57,treadmill,eraser,freeway,videotape
8,compact-disc,chair,rocket,gas
110,compact-disc,chair,rocket,gas
130,treadmill,eraser,freeway,videotape
260,ring,satellite,sword,computer
Ovflow->
Bucket[13]
74,hammer,staircase,table,treadmill
362,bowl,carrot,pillow,school
371,bathtub,zebra,coffee-shop,sunglasses
526,key,baby,baby,cup
673,yawn,swim,crystal,database
707,ears,yellow,maze,highway
770,ears,drink,sword,pants
887,air,bed,ice,telescope
955,child,planet,torch,weapon
966,alphabet,water,baby,air
74,hammer,staircase,table,treadmill
231,shop,planet,set,army
271,backpack,coffee-shop,plane,bird
Ovflow->
Bucket[14]
82,eyes,circus,floodlight,album
132,baby,shower,mouth,shop
257,perfume,aircraft,potato,box
259,maze,aeroplane,torch,telescope
385,x-ray,fork,drill,typewriter
433,freeway,triangle,dress,key
494,spice,planet,pillow,bird
576,x-ray,boss,fan,sandpaper
591,swim,circus,baby,cappuccino
641,sphere,spectrum,yellow,database
723,knife,pocket,win,tunnel
856,square,pebble,roof,finger
894,carrot,carrot,cycle,cave
905,restaurant,sandwich,pillow,computer
916,onion,room,egg,child
962,cat,knife,rock,festival
974,chocolates,hieroglyph,fork,chess-board
82,eyes,circus,floodlight,album
118,eraser,fan,ship,tongue
128,compass,needle,baby,shop
114,earth,airport,cat,oodle
257,bed,airport,eyes,album
333,baby,tiger,rocket,toilet
Ovflow->
Bucket[15]
89,eraser,fan,ship,tongue
134,sandwich,leather,plane,church
155,bed,airport,eyes,album
209,ship,dung,satellite,ears
231,baby,tiger,rocket,toilet
281,electricity,gasp,horse,zoo
374,needle,post,carpet,rainbow
379,rocket,swim,boy,junk
401,aircraft,dress,hose,compact-disc
413,pocket,room,hot,highway
584,drink,gate,space,compact-disc
606,fan,ship,needle,microscope
632,pebble,egg,horoscope,double
719,diamond,umbrella,restaurant,album
746,carrot,cat,parachute,festival
757,zebra,horse,hose,weapon
828,zebra,feather,aeroplane,meat
844,coffee,onion,fork,robot
855,umbrella,vampire,circus,bowl
857,drum,electricity,magnet,cave
943,hose,baby,carpet,weapon
985,rib,mist,pebble,shop
986,tiger,arm,vulture,key
89,eraser,fan,ship,tongue
74,bed,rock,bank,highway
111,eyes,circus,floodlight,album
146,maze,foot,dung,bowl
184,eyes,circus,floodlight,album
234,baby,shower,mouth,shop
311,ship,dung,satellite,ears
361,maze,aeroplane,torch,telescope
383,electricity,gasp,horse,zoo
Ovflow->
Bucket[16]
69,sports-car,clown,backpack,gasp
80,leg,telescope,dog,dress
110,bathroom,cup,dingbat,aeroplane
114,car-race,videotape,tapestry,x-ray
262,woman,ice-cream,chess-board,plane
339,passport,cave,surveyor,yellow
483,meteor,cave,child,bed
486,worm,pants,liquid,jet-fighter
527,solid,comet,car-race,staircase
583,spotlight,typewriter,bathroom,balloon
618,dog,apple,thermometer,fungus
689,shoes,highway,tongue,bed
712,shop,skeleton,book,jet-fighter
764,woman,slave,passport,coffee-shop
831,rainbow,kaleidoscope,map,monster
874,surveyor,clown,kaleidoscope,pepper
967,salt,meat,backpack,barbecue
69,sports-car,clown,backpack,gasp
80,leg,telescope,dog,dress
79,slave,album,tennis,planet
152,slave,album,tennis,planet
182,leg,telescope,dog,dress
212,bathroom,cup,dingbat,aeroplane
339,computer,telescope,bathtub,rib
Bucket[17]
50,slave,album,tennis,planet
287,signature,pendulum,videotape,grapes
316,passport,videotape,highway,mosquito
437,rope,telescope,videotape,tiger
505,snail,key,necklace,car
539,kitchen,album,zoo,ice
792,bottle,elephant,kitchen,milkshake
795,snail,bathtub,highway,spectrum
849,meat,girl,oodle,torch
935,bee,butterfly,finger,baby
50,slave,album,tennis,planet
98,sports-car,clown,backpack,gasp
157,passport,surveyor,tennis,circus
351,paintbrush,hammer,saddle,leather
Bucket[18]
104,car,banana,child,pebble
130,grapes,bathtub,elephant,drink
462,record,air,meteor,carrot
522,set,hammer,tapestry,pebble
586,nail,bowl,gemstone,drink
602,bank,army,paintbrush,mosquito
607,tiger,finger,bowl,fork
670,star,kaleidoscope,videotape,x-ray
684,radar,prison,yawn,tiger
755,pocket,pin,album,torch
822,onion,church,woman,plane
835,spoon,child,apple,spiral
863,fin,garden,desk,chief
879,staircase,ring,liquid,perfume
102,man,pin,woman,mist
104,horoscope,tapestry,cappuccino,sphere
190,spectrum,spotlight,database,monster
199,insect,dog,backpack,diamond
229,horse,hammer,double,set
298,chocolates,telescope,passport,pocket
380,game,shop,money,diamond
397,drum,pin,church,aeroplane
Bucket[19]
75,horoscope,tapestry,cappuccino,sphere
174,electricity,worm,shoes,win
181,potato,butterfly,church,coffee-shop
295,drum,pin,church,aeroplane
311,barbecue,comet,telescope,compass
376,rib,tennis,fruit,dung
445,fan,web,bowl,coffee-shop
465,carpet,ice-cream,ice-cream,eyes
669,drink,ears,backpack,carrot
678,barbecue,web,alphabet,needle
748,zebra,elephant,festival,rocket
788,airforce,toilet,woman,magnet
867,magnet,tongue,saddle,restaurant
75,horoscope,tapestry,cappuccino,sphere
40,circus,surveyor,rope,adult
63,bridge,treadmill,butterfly,post
117,spectrum,spotlight,database,monster
126,insect,dog,backpack,diamond
177,horoscope,tapestry,cappuccino,sphere
206,car,banana,child,pebble
232,grapes,bathtub,elephant,drink
283,potato,butterfly,church,coffee-shop
320,mum,pendulum,snail,planet
372,knife,kaleidoscope,tongue,baby
398,vulture,butterfly,slave,potato
Ovflow->
Bucket[20]
116,oodle,mouth,computer,explosive
153,liquid,mouth,bird,star
182,bowl,water,chisel,fungus
300,meteor,perfume,ice-cream,spiral
447,backpack,baby,car-race,sandwich
514,air,bed,woman,circus
547,box,pillow,key,grapes
631,film,rocket,fruit,mist
825,finger,crystal,woman,bed
891,gemstone,maze,bowl,zebra
919,shoes,rib,sunglasses,pepper
920,junk,pyramid,chess-board,man
128,worm,button,garden,boss
238,sunglasses,chocolates,elephant,table
275,meat,x-ray,computer,balloon
Bucket[21]
94,chisel,x-ray,weapon,gasp
111,leg,spiral,alphabet,torch
112,brain,clock,skeleton,rock
232,yawn,roof,banana,carpet
248,alphabet,jet-fighter,computer,famine
320,hammer,chief,bee,drum
355,pin,swim,oodle,drill
357,garden,pepper,ring,teeth
449,apple,table,sandpaper,vulture
456,snail,boy,film,barbecue
493,typewriter,circus,tennis,torch
503,child,horoscope,brain,square
614,junk,plane,chess-board,pepper
693,album,baby,desk,crystal
714,telescope,grapes,paintbrush,chair
785,child,diamond,fruit,bed
811,cup,spiral,salt,earth
901,cave,baby,elephant,nail
989,window,win,tapestry,pyramid
94,chisel,x-ray,weapon,gasp
81,train,mist,woman,zebra
192,meteor,boy,tunnel,swim
334,yawn,roof,banana,carpet
Ovflow->
Bucket[22]
139,cat,earth,zoo,hot
229,set,spectrum,money,spiral
286,bed,sphere,train,bed
321,room,parachute,slave,hose
358,torch,fin,leg,pillow
520,software,leather,bee,square
531,spoon,balloon,hammer,foot
559,space,man,videotape,airforce
563,game,compass,family,man
610,bed,shower,telescope,swim
682,eyes,game,tapestry,drink
784,drum,mouth,car-race,eraser
793,square,bridge,tennis,electricity
830,fungus,sword,chisel,flower
836,man,arm,oodle,coffee
877,drill,rock,videotape,pepper
888,barbecue,radar,ice-cream,set
976,navy,pebble,dog,maze
31,aeroplane,mum,dog,win
105,egg,foot,vacuum,boy
104,aeroplane,mum,dog,win
258,rifle,knife,girl,chief
358,egg,vampire,apple,carrot
Ovflow->
Bucket[23]
156,rifle,knife,girl,chief
187,star,game,hammer,hat
247,explosive,carrot,school,bank
264,eyes,foot,dog,water
267,compass,navy,worm,torch
354,onion,pith,butterfly,torch
468,aeroplane,feather,computer,vulture
510,umbrella,fungus,army,floodlight
534,insect,ship,cave,magnet
540,electricity,umbrella,slave,sandwich
551,famine,grapes,alphabet,dung
572,eyes,umbrella,money,airport
609,zebra,software,treadmill,balloon
677,wheelchair,famine,shop,baby
727,drink,dress,gemstone,knife
736,fork,drink,shop,spoon
741,roof,feather,alphabet,pepper
794,rifle,ship,solid,spice
839,grapes,airforce,bee,pocket
859,rib,sword,sunglasses,pepper
947,coffee-shop,mosquito,train,game
952,spice,earth,typewriter,milk
94,plane,arm,tapestry,clock
161,dress,record,library,hieroglyph
221,bank,star,air,chocolates
241,cat,earth,zoo,hot
349,explosive,carrot,school,bank
369,compass,navy,worm,torch
387,adult,bank,cup,pocket
Ovflow->
Bucket[24]
85,liquid,map,compass,bridge
151,meteor,tunnel,wheelchair,spiral
297,snail,backpack,cycle,chair
315,comet,tennis,eraser,mist
363,dog,kaleidoscope,drill,yellow
426,bottle,spotlight,baby,bomb
463,bird,paintbrush,insect,bridge
484,highway,salt,coffee-shop,dung
545,church,sun,zebra,aeroplane
663,toilet,slave,explosive,coffee-shop
683,elephant,dog,fungus,freeway
715,prison,brain,teeth,fin
737,cappuccino,typewriter,circus,pepper
800,tunnel,ears,foot,adult
912,passport,solid,square,mist
970,tennis,zoo,horse,drill
85,liquid,map,compass,bridge
67,finger,leg,dress,electricity
114,liquid,map,compass,bridge
140,finger,leg,dress,electricity
293,chisel,printer,carrot,roof
385,dingbat,shop,knife,onion
386,computer,bird,circus,sandwich
Ovflow->
Bucket[25]
5,ears,shop,planet,satellite
108,paintbrush,shop,rifle,fungus
194,meat,cave,grapes,floodlight
204,videotape,book,drink,bed
206,ice-cream,database,software,bed
234,stomach,slave,boy,aeroplane
243,solid,film,planet,egg
283,dingbat,shop,knife,onion
369,film,money,rocket,roof
403,typewriter,church,cat,bridge
421,typewriter,tunnel,star,spice
436,tongue,sun,sphere,famine
512,car-race,army,bank,umbrella
613,army,saddle,sphere,freeway
777,skeleton,fire,sword,barbecue
841,gloves,toilet,aeroplane,sandwich
885,signature,cup,sandwich,coffee-shop
917,film,solid,compass,milk
936,cup,solid,pith,square
993,desk,cave,arm,gasp
5,ears,shop,planet,satellite
89,kitchen,kaleidoscope,hat,aeroplane
5,ears,shop,planet,satellite
187,liquid,map,compass,bridge
281,worm,paintbrush,potato,gate
354,film,prison,sphere,rifle
355,elephant,signature,car,gasp
Bucket[26]
83,bank,library,square,flower
140,bank,sports-car,jet-fighter,swim
238,boss,church,bank,gate
260,pyramid,robot,square,x-ray
415,yellow,saddle,game,rocket
478,plane,bird,boy,hieroglyph
625,gasp,spotlight,umbrella,pyramid
629,adult,girl,aircraft,spoon
688,milk,oodle,circus,yellow
754,fungus,spotlight,car,baby
801,record,database,electricity,pillow
802,diamond,book,rib,baby
83,bank,library,square,flower
132,foot,tongue,feather,bank
141,airforce,car-race,gasp,post
185,bank,library,square,flower
242,bank,sports-car,jet-fighter,swim
263,earth,spotlight,famine,mouth
318,carpet,skeleton,barbecue,cat
Bucket[27]
161,earth,spotlight,famine,mouth
193,table,army,restaurant,post
271,pebble,computer,cat,vampire
323,space,meat,radar,potato
391,umbrella,chess-board,dung,fork
461,vampire,zoo,famine,clock
546,dress,stomach,freeway,shower
642,mouth,robot,planet,milkshake
653,bridge,highway,magnet,hot
771,tiger,skeleton,flower,table
854,zebra,fruit,dress,fan
932,nail,shoes,balloon,wheelchair
979,feather,liquid,coffee-shop,table
112,bank,library,square,flower
261,triangle,spotlight,earth,spice
295,table,army,restaurant,post
362,pyramid,robot,square,x-ray
373,pebble,computer,cat,vampire
Ovflow->
Bucket[28]
58,elephant,satellite,grapes,planet
118,film,adult,spice,boss
128,ice-cream,grapes,zebra,gate
131,meteor,hat,sandwich,spoon
143,salt,nail,car,star
148,videotape,radar,triangle,button
304,train,coffee-shop,pebble,vulture
307,signature,horoscope,aeroplane,monster
460,database,table,aeroplane,circus
474,window,rib,pepper,set
664,guitar,shower,spice,pebble
699,treadmill,teeth,bed,fan
752,family,hat,carrot,bed
759,gemstone,planet,cycle,sandwich
782,snail,sphere,navy,vulture
941,salt,win,bridge,zebra
58,elephant,satellite,grapes,planet
51,meat,diamond,pyramid,sword
110,library,crystal,bed,circle
143,tunnel,square,mosquito,egg
250,videotape,radar,triangle,button
315,apple,balloon,mist,leather
Ovflow->
Bucket[29]
81,library,crystal,bed,circle
221,bathtub,coffee,egg,plane
351,salt,milkshake,dung,navy
398,gas,arm,spectrum,needle
409,box,maze,rock,eyes
481,car-race,balloon,horse,foot
488,cave,monster,potato,mouth
557,library,chocolates,fungus,triangle
566,gemstone,staircase,carrot,hot
573,comet,carpet,software,tiger
604,telescope,onion,room,monster
649,liquid,drink,chair,bed
658,videotape,milk,eraser,bed
813,spotlight,perfume,zebra,spiral
889,money,rifle,drink,torch
965,worm,spice,rib,plane
975,comet,restaurant,crystal,chair
81,library,crystal,bed,circle
95,slave,milk,swim,electricity
168,slave,milk,swim,electricity
264,snail,carrot,square,boy
323,bathtub,coffee,egg,plane
401,shop,navy,umbrella,pebble
Ovflow->
Bucket[30]
6,zebra,circle,spoon,leather
51,bed,drill,aeroplane,parachute
56,sphere,gasp,wheelchair,navy
100,spice,milkshake,milk,sphere
102,rib,chair,pillow,onion
144,airport,hot,rifle,flower
189,clock,aircraft,circus,nail
190,coffee,game,coffee-shop,vampire
199,floodlight,rocket,pebble,swim
263,mist,bridge,bed,sword
338,post,parachute,triangle,airforce
365,car,eraser,drink,earth
538,monster,hat,onion,foot
432,coffee-shop,mum,radar,circus
674,clock,carrot,car,clock
676,barbecue,gate,drill,parachute
937,adult,restaurant,freeway,coffee
6,zebra,circle,spoon,leather
51,bed,drill,aeroplane,parachute
56,sphere,gasp,wheelchair,navy
100,spice,milkshake,milk,sphere
80,bed,drill,aeroplane,parachute
83,tiger,water,hot,tiger
85,sphere,gasp,wheelchair,navy
91,famine,rifle,spoon,circle
6,zebra,circle,spoon,leather
153,bed,drill,aeroplane,parachute
280,leather,floodlight,carpet,pillow
286,maze,nail,airport,yellow
300,roof,horoscope,earth,torch
365,mist,bridge,bed,sword
396,satellite,pyramid,rifle,shower
Ovflow->
Bucket[31]
9,spiral,chocolates,grapes,barbecue
20,gate,rocket,dress,horoscope
117,jet-fighter,boss,sandwich,milkshake
126,shower,floodlight,chair,bed
135,umbrella,chair,circle,pocket
184,maze,nail,airport,yellow
383,button,balloon,zebra,bed
419,yellow,fan,staircase,horoscope
438,perfume,roof,staircase,win
543,pocket,hose,rifle,win
600,compass,planet,circus,airport
660,vampire,fan,flower,eyes
696,hieroglyph,pith,carrot,circus
749,pocket,foot,needle,fin
772,spice,compass,bed,milkshake
847,bed,drum,gasp,teeth
938,chair,bank,crystal,cycle
9,spiral,chocolates,grapes,barbecue
20,gate,rocket,dress,horoscope
35,zebra,circle,spoon,leather
9,spiral,chocolates,grapes,barbecue
20,gate,rocket,dress,horoscope
108,zebra,circle,spoon,leather
111,spiral,chocolates,grapes,barbecue
117,eyes,hat,bridge,spice
156,tiger,water,hot,tiger
188,cat,circus,spoon,spectrum
204,rib,chair,pillow,onion
209,star,spectrum,win,pith
219,jet-fighter,boss,sandwich,milkshake
246,airport,hot,rifle,flower
316,electricity,fan,needle,maze
Ovflow->
376,rib,win,arm,chief
391,roof,game,airport,fan
Bucket[32]
210,tennis,shoes,torpedo,necklace
215,cup,slave,garden,rope
325,snail,pin,passport,compact-disc
637,kitchen,dingbat,fire,sun
686,web,window,train,guitar
864,dog,comet,solid,money
101,tapestry,kaleidoscope,liquid,liquid
303,tapestry,brain,train,garden
317,cup,slave,garden,rope
400,shoes,desk,spotlight,woman
Bucket[33]
19,brain,butterfly,ears,guitar
29,highway,bottle,compact-disc,compact-disc
72,tapestry,kaleidoscope,liquid,liquid
186,microscope,computer,junk,signature
201,tapestry,brain,train,garden
515,tapestry,ring,slave,car-race
536,banana,database,paintbrush,comet
549,air,bathtub,liquid,database
561,vacuum,oodle,printer,car-race
585,shoes,highway,solid,bird
589,compact-disc,cave,chisel,skeleton
654,sunglasses,junk,cup,ears
716,chess-board,zoo,map,desk
734,torpedo,bottle,backpack,highway
881,guitar,tennis,compact-disc,meteor
990,stomach,compact-disc,surveyor,cappuccino
19,brain,butterfly,ears,guitar
29,highway,bottle,compact-disc,compact-disc
72,tapestry,kaleidoscope,liquid,liquid
48,brain,butterfly,ears,guitar
19,brain,butterfly,ears,guitar
207,necklace,key,television,compact-disc
294,computer,hammer,robot,necklace
312,tennis,shoes,torpedo,necklace
352,kitchen,fruit,kaleidoscope,meteor
Bucket[34]
87,coffee,tunnel,money,woman
113,rifle,torpedo,vacuum,printer
166,maze,family,key,ring
327,perfume,database,fire,elephant
390,mosquito,telescope,child,weapon
412,hot,car-race,tapestry,shoes
423,man,family,telescope,bee
548,mosquito,dingbat,gloves,chess-board
588,boy,tennis,shop,meteor
595,leather,comet,leg,pendulum
611,boy,elephant,yawn,zoo
705,roof,tapestry,festival,army
767,drill,thermometer,pin,pendulum
778,planet,window,typewriter,solid
833,ship,slave,printer,ice-cream
843,fungus,typewriter,zoo,torpedo
873,insect,church,girl,pin
931,bed,worm,chess-board,garden
997,baby,butterfly,festival,thermometer
87,coffee,tunnel,money,woman
127,plane,compact-disc,bowl,map
119,drink,thermometer,sandpaper,army
200,plane,compact-disc,bowl,map
215,rifle,torpedo,vacuum,printer
224,drill,skeleton,family,double
279,clock,skeleton,tongue,bird
395,dress,videotape,leg,fire
Bucket[35]
48,needle,ring,map,library
122,drill,skeleton,family,double
266,eyes,compact-disc,gloves,surveyor
617,rifle,cup,torpedo,apple
805,game,sports-car,school,telescope
977,adult,sports-car,pin,thermometer
987,sphere,gloves,film,oodle
48,needle,ring,map,library
77,needle,ring,map,library
86,satellite,alphabet,pants,skeleton
150,needle,ring,map,library
159,satellite,alphabet,pants,skeleton
173,spoon,database,backpack,gloves
268,maze,family,key,ring
290,barbecue,bathtub,spotlight,salt
368,eyes,compact-disc,gloves,surveyor
Bucket[36]
395,zoo,adult,ice-cream,web
550,gemstone,pepper,salt,banana
659,box,fungus,pin,thermometer
694,dog,grapes,prison,worm
708,hammer,baby,telescope,chess-board
808,pants,plane,rope,microscope
853,church,pyramid,chisel,map
871,cappuccino,eraser,brain,printer
991,bee,circus,meat,sports-car
1000,signature,barbecue,desk,alphabet
64,box,triangle,sun,apple
137,box,triangle,sun,apple
270,map,compass,pin,bathtub
310,junk,fork,brain,film
Bucket[37]
32,fruit,needle,dog,torpedo
195,money,sword,backpack,tennis
208,junk,fork,brain,film
255,girl,staircase,robot,highway
272,passport,record,cappuccino,database
276,family,insect,paintbrush,finger
277,leg,post,tapestry,database
554,web,spectrum,tapestry,bathtub
700,car-race,chocolates,dog,guitar
729,chisel,sword,cave,butterfly
818,saddle,coffee,elephant,comet
840,meat,pith,worm,microscope
946,sandpaper,mist,printer,apple
32,fruit,needle,dog,torpedo
65,kitchen,coffee-shop,compact-disc,vacuum
378,family,insect,paintbrush,finger
Bucket[38]
14,diamond,gate,meat,fruit
33,milk,zebra,dingbat,skeleton
42,sandwich,rifle,web,bowl
101,software,rocket,web,woman
115,zebra,staircase,telescope,oodle
170,pillow,insect,clown,banana
282,pepper,satellite,guitar,cave
381,umbrella,flower,chess-board,signature
428,bed,diamond,microscope,air
431,feather,torch,alphabet,fruit
597,record,onion,pendulum,surveyor
605,hat,fan,printer,web
743,spectrum,diamond,money,hammer
747,gasp,staircase,key,worm
768,milkshake,rock,festival,hammer
883,chief,room,treadmill,shop
978,spoon,bed,gloves,chisel
988,umbrella,wheelchair,rope,rainbow
14,diamond,gate,meat,fruit
33,milk,zebra,dingbat,skeleton
42,sandwich,rifle,web,bowl
42,arm,spice,oodle,alphabet
47,star,airport,gemstone,ears
60,water,diamond,pendulum,sun
62,milk,zebra,dingbat,skeleton
14,diamond,gate,meat,fruit
103,triangle,pith,comet,signature
115,arm,spice,oodle,alphabet
120,star,airport,gemstone,ears
227,hot,shower,money,banana
299,car,barbecue,compact-disc,fire
382,post,onion,bowl,dingbat
Ovflow->
390,ice,balloon,videotape,signature
Bucket[39]
1,triangle,pith,comet,signature
13,arm,spice,oodle,alphabet
18,star,airport,gemstone,ears
125,hot,shower,money,banana
197,car,barbecue,compact-disc,fire
202,milk,onion,shoes,finger
203,horoscope,bank,computer,pin
205,chair,shower,ring,thermometer
322,plane,post,clown,tapestry
326,staircase,record,database,cup
352,chief,dress,rope,tennis
429,hat,perfume,sports-car,finger
500,bridge,ship,vacuum,backpack
516,pebble,potato,tongue,paintbrush
553,mum,boy,cave,sunglasses
627,vulture,clock,worm,slave
807,milkshake,baby,double,rope
816,chief,eraser,church,necklace
827,navy,fan,worm,tennis
914,monster,leather,comet,computer
1,triangle,pith,comet,signature
13,arm,spice,oodle,alphabet
18,star,airport,gemstone,ears
30,triangle,pith,comet,signature
43,diamond,gate,meat,fruit
92,milk,rifle,garden,festival
1,triangle,pith,comet,signature
13,arm,spice,oodle,alphabet
18,star,airport,gemstone,ears
203,software,rocket,web,woman
217,zebra,staircase,telescope,oodle
272,pillow,insect,clown,banana
Ovflow->
305,horoscope,bank,computer,pin
343,egg,teeth,videotape,garden
384,pepper,satellite,guitar,cave
Bucket[40]
3,finger,desk,mosquito,finger
25,dog,robot,insect,book
47,school,printer,button,sandpaper
291,clown,leg,leather,robot
308,bathroom,saddle,flower,toilet
567,film,book,jet-fighter,oodle
646,family,car-race,rocket,meat
806,sandpaper,church,leather,church
814,sports-car,kitchen,diamond,pendulum
981,school,air,crystal,vacuum
3,finger,desk,mosquito,finger
25,dog,robot,insect,book
47,school,printer,button,sandpaper
45,pants,stomach,clock,gemstone
76,school,printer,button,sandpaper
96,kaleidoscope,pendulum,set,woman
3,finger,desk,mosquito,finger
127,dog,robot,insect,book
Bucket[41]
160,sandpaper,junk,insect,cup
269,alphabet,skeleton,balloon,desk
312,highway,key,chief,woman
329,elephant,pin,swim,weapon
366,tunnel,army,chocolates,bathtub
399,clown,bee,wheelchair,double
448,family,ring,balloon,apple
509,salt,bee,shower,robot
565,highway,army,feather,shop
652,signature,ears,horoscope,compact-disc
672,album,dingbat,spiral,printer
726,telescope,finger,onion,butterfly
824,tennis,key,sandwich,sandpaper
845,family,butterfly,staircase,typewriter
930,clown,kaleidoscope,restaurant,signature
948,skeleton,desk,plane,shoes
32,finger,desk,mosquito,finger
54,dog,robot,insect,book
109,brain,printer,pocket,school
123,skeleton,brain,jet-fighter,apple
169,kaleidoscope,pendulum,set,woman
251,compact-disc,necklace,eyes,meteor
Bucket[42]
147,satellite,tapestry,circle,banana
236,diamond,chisel,explosive,dingbat
303,ship,skeleton,chocolates,ring
470,star,videotape,record,child
475,star,weapon,software,bird
479,leather,guitar,clock,saddle
482,adult,family,boy,bee
517,set,printer,earth,vacuum
521,gasp,girl,circus,gemstone
525,star,toilet,knife,garden
692,grapes,album,boss,vacuum
721,compass,double,magnet,fire
740,explosive,cave,mouth,bottle
745,ship,robot,mosquito,tennis
872,spectrum,treadmill,coffee,necklace
893,post,sunglasses,star,prison
902,hot,sports-car,satellite,weapon
926,baby,kitchen,umbrella,banana
968,vulture,toilet,boy,sunglasses
124,torch,shop,fork,ring
142,yellow,typewriter,mosquito,meat
249,satellite,tapestry,circle,banana
Bucket[43]
43,pebble,backpack,car,fire
53,diamond,ears,rib,worm
427,carrot,television,spectrum,tongue
451,crystal,window,room,key
453,water,spotlight,yellow,television
575,mist,bathtub,hat,rope
578,fan,butterfly,explosive,banana
579,hose,surveyor,horse,apple
620,navy,robot,sword,telescope
623,coffee-shop,army,nail,bathroom
628,chair,bee,pocket,surveyor
704,nail,car-race,famine,treadmill
815,spectrum,meat,feather,gas
834,explosive,comet,vulture,tongue
43,pebble,backpack,car,fire
53,diamond,ears,rib,worm
53,tiger,brain,win,chess-board
72,pebble,backpack,car,fire
107,floodlight,fruit,rocket,hammer
180,floodlight,fruit,rocket,hammer
197,torch,shop,fork,ring
337,bed,salt,rifle,printer
Bucket[44]
49,slave,bed,barbecue,signature
137,bird,explosive,torch,signature
158,ring,satellite,sword,computer
200,garden,mum,hat,desk
224,sunglasses,bomb,set,treadmill
244,solid,win,mum,album
254,banana,adult,staircase,fruit
317,sandpaper,carpet,cat,tongue
335,cappuccino,space,milkshake,spotlight
418,stomach,baby,eyes,woman
458,chess-board,nail,milk,gemstone
487,apple,room,circus,salt
491,salt,planet,mosquito,chess-board
501,clown,barbecue,clock,double
615,database,drink,adult,library
733,solid,mist,magnet,printer
656,bathroom,planet,horoscope,necklace
730,compact-disc,vulture,adult,rope
832,window,magnet,mist,family
49,slave,bed,barbecue,signature
66,necklace,hot,cat,weapon
103,hammer,staircase,table,treadmill
113,butterfly,aircraft,satellite,compact-disc
120,tennis,aeroplane,coffee-shop,dog
163,slave,freeway,x-ray,tunnel
170,book,hieroglyph,compass,butterfly
176,hammer,staircase,table,treadmill
223,videotape,bed,post,bee
239,bird,explosive,torch,signature
254,pin,potato,chief,prison
Ovflow->
282,pants,grapes,plane,butterfly
327,train,ice,flower,sandpaper
348,stomach,arm,sword,chess-board
Bucket[45]
28,treadmill,eraser,freeway,videotape
68,book,hieroglyph,compass,butterfly
84,butterfly,aircraft,satellite,compact-disc
92,double,coffee,leather,snail
129,shop,planet,set,army
164,tongue,monster,monster,kaleidoscope
169,backpack,coffee-shop,plane,bird
180,pants,grapes,plane,butterfly
225,train,ice,flower,sandpaper
268,meteor,sphere,button,dingbat
309,ring,space,rocket,oodle
319,girl,vulture,adult,box
328,guitar,rock,sword,gas
367,bird,post,gate,girl
384,church,fork,foot,tennis
425,saddle,spice,crystal,sports-car
439,pendulum,sword,parachute,bird
497,book,spectrum,pith,solid
650,yawn,barbecue,perfume,thermometer
661,apple,button,arm,television
28,treadmill,eraser,freeway,videotape
68,book,hieroglyph,compass,butterfly
84,butterfly,aircraft,satellite,compact-disc
92,double,coffee,leather,snail
39,shoes,rifle,drum,bowl
90,slave,freeway,x-ray,tunnel
97,book,hieroglyph,compass,butterfly
129,map,water,software,vacuum
186,butterfly,aircraft,satellite,compact-disc
266,tongue,monster,monster,kaleidoscope
Ovflow->
326,sunglasses,bomb,set,treadmill
356,banana,adult,staircase,fruit
Bucket[46]
44,maze,foot,dung,bowl
45,bed,rock,bank,highway
64,fin,pebble,chief,bird
103,umbrella,diamond,milkshake,signature
341,bank,software,radar,girl
404,x-ray,man,game,air
405,baby,cycle,swim,ring
457,crystal,bed,aircraft,zoo
506,onion,boss,set,festival
560,cycle,spoon,chief,sports-car
570,flower,crystal,sandwich,shoes
571,insect,explosive,dress,butterfly
612,carrot,rock,spiral,sunglasses
633,freeway,freeway,circus,school
735,pith,ice,vampire,web
781,leather,cycle,boy,tongue
812,coffee-shop,aeroplane,perfume,tapestry
899,aeroplane,eyes,clock,paintbrush
903,software,arm,man,guitar
922,roof,adult,rib,butterfly
925,fungus,spoon,hot,gas
942,airport,eyes,rib,bottle
44,maze,foot,dung,bowl
45,bed,rock,bank,highway
64,fin,pebble,chief,bird
41,earth,airport,cat,oodle
73,maze,foot,dung,bowl
93,fin,pebble,chief,bird
147,bed,rock,bank,highway
166,fin,pebble,chief,bird
211,insect,pocket,pebble,girl
236,sandwich,leather,plane,church
273,bridge,pebble,chocolates,alphabet
359,perfume,aircraft,potato,box
Bucket[47]
12,earth,airport,cat,oodle
99,compass,needle,baby,shop
109,insect,pocket,pebble,girl
171,bridge,pebble,chocolates,alphabet
414,perfume,satellite,horse,television
441,horse,bed,spice,highway
469,onion,mum,carpet,double
587,coffee,table,mum,database
634,circle,magnet,roof,garden
638,mum,knife,gate,chess-board
671,magnet,diamond,circus,videotape
809,carpet,drink,grapes,prison
954,dung,floodlight,sandwich,liquid
12,earth,airport,cat,oodle
99,compass,needle,baby,shop
12,earth,airport,cat,oodle
191,eraser,fan,ship,tongue
201,compass,needle,baby,shop
205,umbrella,diamond,milkshake,signature
Bucket[48]
55,passport,surveyor,tennis,circus
124,album,finger,skeleton,ship
183,ice-cream,microscope,highway,coffee
223,typewriter,bathroom,skeleton,famine
237,computer,telescope,bathtub,rib
249,paintbrush,hammer,saddle,leather
507,church,meat,saddle,nail
511,bee,cave,church,maze
556,telescope,chess-board,gloves,button
608,desk,elephant,gas,mouth
766,worm,pin,fruit,plane
803,hammer,butterfly,sun,potato
898,ears,comet,clown,wheelchair
55,passport,surveyor,tennis,circus
285,ice-cream,microscope,highway,coffee
325,typewriter,bathroom,skeleton,famine
389,signature,pendulum,videotape,grapes
Bucket[49]
356,rope,alphabet,cup,foot
364,liquid,map,fire,cat
368,sun,telescope,meat,x-ray
593,meteor,prison,compact-disc,flower
636,apple,bathtub,zoo,drum
662,pendulum,meteor,chess-board,software
666,dog,finger,printer,pith
706,signature,chess-board,torpedo,vampire
773,money,desk,tongue,software
870,bee,school,banana,rifle
84,passport,surveyor,tennis,circus
109,leg,telescope,dog,dress
171,sports-car,clown,backpack,gasp
216,car-race,videotape,tapestry,x-ray
226,album,finger,skeleton,ship
364,woman,ice-cream,chess-board,plane
Bucket[50]
34,bridge,treadmill,butterfly,post
73,man,pin,woman,mist
88,spectrum,spotlight,database,monster
93,satellite,yawn,train,carrot
127,horse,hammer,double,set
175,airport,dingbat,book,spectrum
218,mum,pendulum,snail,planet
270,knife,kaleidoscope,tongue,baby
392,spice,printer,desk,software
394,wheelchair,gloves,clown,crystal
499,set,bee,slave,bridge
524,monster,treadmill,oodle,electricity
621,record,treadmill,library,cat
622,monster,rainbow,army,bank
964,triangle,dingbat,vacuum,adult
34,bridge,treadmill,butterfly,post
73,man,pin,woman,mist
88,spectrum,spotlight,database,monster
93,satellite,yawn,train,carrot
113,circus,surveyor,rope,adult
136,bridge,treadmill,butterfly,post
175,man,pin,woman,mist
335,chief,hammer,cappuccino,shower
Bucket[51]
11,circus,surveyor,rope,adult
97,insect,dog,backpack,diamond
196,chocolates,telescope,passport,pocket
233,chief,hammer,cappuccino,shower
278,game,shop,money,diamond
296,vulture,butterfly,slave,potato
305,dress,box,bowl,drum
454,airforce,hammer,rainbow,eyes
562,pocket,snail,junk,bed
569,ship,necklace,shop,gasp
582,milkshake,school,kitchen,bomb
598,man,school,stomach,fork
675,rock,prison,car-race,boss
680,set,oodle,girl,sandwich
681,horoscope,train,cup,post
728,explosive,treadmill,bee,mist
739,umbrella,cup,window,car
829,rifle,church,thermometer,drum
858,baby,pants,hammer,rocket
953,roof,key,robot,rock
907,grapes,printer,spotlight,cat
951,sandwich,shoes,dog,staircase
11,circus,surveyor,rope,adult
97,insect,dog,backpack,diamond
122,satellite,yawn,train,carrot
11,circus,surveyor,rope,adult
195,satellite,yawn,train,carrot
276,electricity,worm,shoes,win
277,airport,dingbat,book,spectrum
Bucket[52]
52,train,mist,woman,zebra
120,ears,arm,car-race,yellow
136,sunglasses,chocolates,elephant,table
227,treadmill,egg,passport,restaurant
245,bird,planet,window,horse
310,train,arm,slave,triangle
313,pants,drum,dingbat,compass
389,banana,crystal,treadmill,feather
400,air,coffee-shop,elephant,monster
411,television,restaurant,shoes,sword
577,videotape,bomb,garden,electricity
667,school,mist,map,vampire
718,thermometer,torch,key,leather
775,cave,eraser,money,win
791,pin,drum,train,chief
796,window,pyramid,elephant,floodlight
921,fruit,coffee,map,circle
52,train,mist,woman,zebra
55,worm,button,garden,boss
106,sun,crystal,snail,aeroplane
119,meteor,boy,tunnel,swim
179,sun,crystal,snail,aeroplane
214,brain,clock,skeleton,rock
218,oodle,mouth,computer,explosive
222,ears,arm,car-race,yellow
284,bowl,water,chisel,fungus
347,bird,planet,window,horse
350,alphabet,jet-fighter,computer,famine
Bucket[53]
26,worm,button,garden,boss
70,train,boy,pants,rock
77,sun,crystal,snail,aeroplane
90,meteor,boy,tunnel,swim
173,meat,x-ray,computer,balloon
251,salt,bridge,sun,man
343,torpedo,horoscope,toilet,potato
430,cave,ship,skeleton,restaurant
552,window,jet-fighter,telescope,cat
635,worm,vulture,chess-board,car
751,gloves,ship,vacuum,coffee
798,kaleidoscope,triangle,church,foot
823,saddle,mouth,ears,carrot
852,vacuum,sphere,stomach,diamond
865,meat,egg,woman,star
26,worm,button,garden,boss
70,train,boy,pants,rock
77,sun,crystal,snail,aeroplane
90,meteor,boy,tunnel,swim
99,train,boy,pants,rock
123,chisel,x-ray,weapon,gasp
154,train,mist,woman,zebra
172,train,boy,pants,rock
196,chisel,x-ray,weapon,gasp
213,leg,spiral,alphabet,torch
255,liquid,mouth,bird,star
329,treadmill,egg,passport,restaurant
353,salt,bridge,sun,man
402,meteor,perfume,ice-cream,spiral
Bucket[54]
2,aeroplane,mum,dog,win
23,rifle,spectrum,printer,earth
76,egg,foot,vacuum,boy
119,bank,star,air,chocolates
167,gasp,baby,library,button
176,knife,yellow,television,spice
220,man,airport,prison,mist
228,eyes,dress,kitchen,potato
285,adult,bank,cup,pocket
330,drum,eyes,bathtub,fan
347,balloon,sandwich,ice-cream,rifle
350,jet-fighter,drill,gas,freeway
359,carrot,space,clown,famine
442,post,plane,surveyor,floodlight
498,floodlight,boss,dog,fin
518,electricity,feather,ears,pocket
574,x-ray,circle,film,needle
599,circus,button,signature,explosive
679,coffee,compass,snail,knife
710,bridge,radar,bottle,mouth
862,coffee,cat,church,car
900,sandwich,eraser,clown,planet
913,software,hot,solid,adult
2,aeroplane,mum,dog,win
23,rifle,spectrum,printer,earth
76,egg,foot,vacuum,boy
33,spectrum,circle,army,torch
52,rifle,spectrum,printer,earth
88,dress,record,library,hieroglyph
2,aeroplane,mum,dog,win
106,spectrum,circle,army,torch
167,plane,arm,tapestry,clock
178,egg,foot,vacuum,boy
252,car,rock,skeleton,bridge
Ovflow->
289,star,game,hammer,hat
330,eyes,dress,kitchen,potato
Bucket[55]
4,spectrum,circle,army,torch
59,dress,record,library,hieroglyph
65,plane,arm,tapestry,clock
150,car,rock,skeleton,bridge
226,fan,gate,fruit,fin
256,egg,vampire,apple,carrot
336,leather,gasp,comet,barbecue
345,rock,diamond,rope,pebble
378,vulture,room,pin,airport
489,teeth,floodlight,church,teeth
513,software,torch,family,fork
535,x-ray,mum,festival,coffee
544,wheelchair,dung,church,navy
651,car,mum,bathroom,mist
687,hose,water,typewriter,clock
744,milk,mum,cup,vampire
756,circus,flower,tapestry,boss
760,bed,potato,bathroom,insect
895,crystal,roof,army,mosquito
909,fan,fork,compact-disc,space
957,bed,roof,pendulum,rib
999,pocket,bank,map,x-ray
4,spectrum,circle,army,torch
59,dress,record,library,hieroglyph
65,plane,arm,tapestry,clock
4,spectrum,circle,army,torch
125,rifle,spectrum,printer,earth
269,gasp,baby,library,button
278,knife,yellow,television,spice
322,man,airport,prison,mist
328,fan,gate,fruit,fin
331,set,spectrum,money,spiral
366,eyes,foot,dog,water
388,bed,sphere,train,bed
Bucket[56]
60,kitchen,kaleidoscope,hat,aeroplane
96,stomach,tennis,diamond,carrot
179,worm,paintbrush,potato,gate
211,spotlight,cappuccino,insect,airforce
252,film,prison,sphere,rifle
279,zoo,window,horse,parachute
284,computer,bird,circus,sandwich
292,paintbrush,web,rifle,swim
450,shoes,stomach,mosquito,dung
477,surveyor,robot,gate,record
541,passport,key,potato,feather
665,fruit,rope,software,eyes
761,thermometer,apple,dress,dress
838,oodle,videotape,crystal,dress
875,bottle,ice-cream,electricity,circus
945,sandpaper,girl,electricity,cat
60,kitchen,kaleidoscope,hat,aeroplane
96,stomach,tennis,diamond,carrot
34,ears,shop,planet,satellite
210,paintbrush,shop,rifle,fungus
306,videotape,book,drink,bed
308,ice-cream,database,software,bed
313,spotlight,cappuccino,insect,airforce
381,zoo,window,horse,parachute
394,paintbrush,web,rifle,swim
Bucket[57]
38,finger,leg,dress,electricity
191,chisel,printer,carrot,roof
253,elephant,signature,car,gasp
353,meteor,ring,set,post
406,microscope,torpedo,drink,aeroplane
472,comet,shop,x-ray,fork
581,gemstone,bird,car,pocket
626,bowl,sports-car,eraser,win
928,web,bowl,hat,feather
929,family,web,space,earth
972,dingbat,album,arm,leather
38,finger,leg,dress,electricity
125,stomach,tennis,diamond,carrot
107,ears,shop,planet,satellite
162,kitchen,kaleidoscope,hat,aeroplane
198,stomach,tennis,diamond,carrot
253,meteor,tunnel,wheelchair,spiral
296,meat,cave,grapes,floodlight
336,stomach,slave,boy,aeroplane
345,solid,film,planet,egg
399,snail,backpack,cycle,chair
Bucket[58]
106,roof,cup,set,circus
239,bed,alphabet,earth,explosive
301,mouth,woman,chair,mosquito
306,fork,church,diamond,game
348,planet,passport,hat,rocket
410,horse,hammer,maze,pillow
420,sandwich,weapon,ice,fungus
476,milkshake,album,dung,button
495,flower,bee,square,software
624,water,torpedo,triangle,plane
655,chair,fire,fin,drill
722,water,bowl,maze,pebble
753,button,woman,wheelchair,milkshake
896,plane,shop,eraser,horse
911,diamond,map,potato,eraser
998,floodlight,church,drill,rock
332,circle,worm,table,fork
341,bed,alphabet,earth,explosive
Bucket[59]
30,foot,tongue,feather,bank
39,airforce,car-race,gasp,post
159,triangle,spotlight,earth,spice
216,carpet,skeleton,barbecue,cat
230,circle,worm,table,fork
265,fungus,typewriter,explosive,arm
402,water,prison,insect,water
446,umbrella,videotape,hieroglyph,sphere
492,fork,army,room,spice
502,room,stomach,flower,feather
732,coffee,spotlight,vampire,grapes
780,maze,yawn,fin,fan
787,sword,skeleton,drum,pith
799,hot,finger,mist,square
897,hot,paintbrush,parachute,boy
949,coffee-shop,alphabet,aeroplane,crystal
958,gate,comet,aeroplane,gasp
969,rib,butterfly,dung,swim
995,potato,computer,boss,onion
30,foot,tongue,feather,bank
39,airforce,car-race,gasp,post
59,foot,tongue,feather,bank
68,airforce,car-race,gasp,post
208,roof,cup,set,circus
340,boss,church,bank,gate
367,fungus,typewriter,explosive,arm
Bucket[60]
41,tunnel,square,mosquito,egg
66,slave,milk,swim,electricity
142,backpack,electricity,freeway,crystal
273,passport,hot,drum,chocolates
299,shop,navy,umbrella,pebble
382,album,eyes,rock,needle
407,zoo,cycle,dress,diamond
417,cup,gate,man,rifle
440,hammer,drill,mist,bank
596,fire,man,carpet,needle
668,cappuccino,car,diamond,chief
685,desk,adult,vampire,eyes
742,robot,bed,bank,feather
765,kaleidoscope,explosive,chief,fin
908,computer,drum,bank,post
41,tunnel,square,mosquito,egg
66,slave,milk,swim,electricity
87,elephant,satellite,grapes,planet
124,meat,diamond,pyramid,sword
183,library,crystal,bed,circle
220,film,adult,spice,boss
244,backpack,electricity,freeway,crystal
245,salt,nail,car,star
Bucket[61]
22,meat,diamond,pyramid,sword
154,dingbat,wheelchair,mum,diamond
162,snail,carrot,square,boy
172,guitar,set,shower,x-ray
213,apple,balloon,mist,leather
324,saddle,foot,coffee-shop,roof
331,bottle,set,zebra,star
555,hammer,fin,ship,cycle
564,printer,adult,post,chair
590,train,radar,bridge,yellow
779,zoo,dung,pocket,spice
783,box,fungus,chair,game
817,paintbrush,pebble,cycle,crystal
860,treadmill,vampire,button,boss
880,tapestry,x-ray,clock,feather
882,bird,rocket,carrot,hot
915,girl,earth,post,pocket
22,meat,diamond,pyramid,sword
70,tunnel,square,mosquito,egg
160,elephant,satellite,grapes,planet
230,ice-cream,grapes,zebra,gate
233,meteor,hat,sandwich,spoon
256,dingbat,wheelchair,mum,diamond
274,guitar,set,shower,x-ray
375,passport,hot,drum,chocolates
Bucket[62]
15,eyes,hat,bridge,spice
62,famine,rifle,spoon,circle
163,chief,gasp,car,bridge
178,leather,floodlight,carpet,pillow
214,electricity,fan,needle,maze
222,spice,car,grapes,baby
289,roof,game,airport,fan
332,fork,coffee,milkshake,carrot
424,baby,explosive,drum,dung
496,planet,sandwich,parachute,magnet
690,star,airforce,flower,gasp
702,circus,fan,crystal,square
709,square,space,hat,drink
724,planet,satellite,chief,hieroglyph
774,car,drill,record,record
846,famine,barbecue,circus,ship
959,x-ray,maze,compass,baby
992,famine,horse,milkshake,airport
15,eyes,hat,bridge,spice
62,famine,rifle,spoon,circle
44,eyes,hat,bridge,spice
49,gate,rocket,dress,horoscope
115,cat,circus,spoon,spectrum
15,eyes,hat,bridge,spice
158,sphere,gasp,wheelchair,navy
228,shower,floodlight,chair,bed
237,umbrella,chair,circle,pocket
291,clock,aircraft,circus,nail
292,coffee,game,coffee-shop,vampire
301,floodlight,rocket,pebble,swim
392,fungus,horse,ship,post
Bucket[63]
54,tiger,water,hot,tiger
86,cat,circus,spoon,spectrum
107,star,spectrum,win,pith
123,parachute,circus,boy,hose
198,roof,horoscope,earth,torch
207,coffee,post,vampire,pebble
217,bank,spoon,roof,circus
274,rib,win,arm,chief
290,fungus,horse,ship,post
294,satellite,pyramid,rifle,shower
337,arm,famine,dress,navy
340,freeway,pocket,car,satellite
375,electricity,spoon,fin,gasp
388,wheelchair,rib,barbecue,car
455,jet-fighter,square,bank,balloon
467,maze,tiger,famine,arm
508,drink,potato,perfume,knife
645,hot,navy,sandwich,drink
647,horse,restaurant,sword,balloon
691,drink,ship,arm,coffee
790,gasp,cycle,boy,man
861,parachute,navy,perfume,sword
884,eyes,spiral,baby,table
950,parachute,rifle,fin,eraser
956,torch,sphere,rocket,fork
983,egg,sword,fin,button
54,tiger,water,hot,tiger
86,cat,circus,spoon,spectrum
38,spiral,chocolates,grapes,barbecue
129,spice,milkshake,milk,sphere
122,gate,rocket,dress,horoscope
164,famine,rifle,spoon,circle
202,spice,milkshake,milk,sphere
225,parachute,circus,boy,hose
Ovflow->
265,chief,gasp,car,bridge
309,coffee,post,vampire,pebble
319,bank,spoon,roof,circus
324,spice,car,grapes,baby
Bucket[64]
105,necklace,key,television,compact-disc
250,kitchen,fruit,kaleidoscope,meteor
258,garden,cappuccino,train,fruit
298,shoes,desk,spotlight,woman
480,highway,highway,book,typewriter
711,finger,fire,highway,vacuum
58,highway,bottle,compact-disc,compact-disc
121,brain,butterfly,ears,guitar
131,highway,bottle,compact-disc,compact-disc
Bucket[65]
192,computer,hammer,robot,necklace
532,woman,alphabet,vacuum,banana
717,solid,clown,microscope,tunnel
360,garden,cappuccino,train,fruit
Bucket[66]
57,satellite,alphabet,pants,skeleton
293,dress,videotape,leg,fire
318,horoscope,church,bathroom,signature
848,umbrella,pin,gemstone,pants
868,star,tapestry,solid,ring
57,satellite,alphabet,pants,skeleton
116,coffee,tunnel,money,woman
189,coffee,tunnel,money,woman
342,satellite,pendulum,saddle,chess-board
Bucket[67]
98,plane,compact-disc,bowl,map
177,clock,skeleton,tongue,bird
240,satellite,pendulum,saddle,chess-board
918,aircraft,computer,skeleton,meat
933,square,skeleton,pendulum,television
939,earth,girl,tongue,telescope
98,plane,compact-disc,bowl,map
Bucket[68]
36,kitchen,coffee-shop,compact-disc,vacuum
133,meteor,boy,bathtub,money
869,highway,radar,money,treadmill
934,dingbat,sphere,church,highway
944,stomach,baby,slave,bird
963,gas,table,ears,money
36,kitchen,coffee-shop,compact-disc,vacuum
61,fruit,needle,dog,torpedo
138,kitchen,coffee-shop,compact-disc,vacuum
235,meteor,boy,bathtub,money
Bucket[69]
168,map,compass,pin,bathtub
408,ice-cream,needle,bathroom,junk
519,shoes,satellite,child,torpedo
630,bird,electricity,tennis,elephant
134,fruit,needle,dog,torpedo
374,passport,record,cappuccino,database
379,leg,post,tapestry,database
Bucket[70]
280,post,onion,bowl,dingbat
302,plane,table,family,chisel
558,bank,foot,computer,garden
738,bridge,hose,festival,saddle
797,airforce,x-ray,microscope,gloves
961,torch,milk,shoes,church
996,horse,staircase,dog,gloves
71,sandwich,rifle,web,bowl
144,sandwich,rifle,web,bowl
165,milk,rifle,garden,festival
259,famine,sandwich,window,salt
304,milk,onion,shoes,finger
Bucket[71]
63,milk,rifle,garden,festival
157,famine,sandwich,window,salt
241,egg,teeth,videotape,garden
288,ice,balloon,videotape,signature
334,fin,tiger,child,worm
360,eyes,chocolates,ice-cream,bowl
373,carpet,milkshake,ice-cream,bathroom
387,drill,navy,solid,window
434,zebra,nail,stomach,car-race
640,fin,grapes,paintbrush,yawn
820,baby,potato,bottle,brain
876,famine,fin,tongue,alphabet
892,onion,carrot,bottle,fire
63,milk,rifle,garden,festival
135,milk,zebra,dingbat,skeleton
Bucket[72]
16,pants,stomach,clock,gemstone
67,kaleidoscope,pendulum,set,woman
145,slave,paintbrush,button,guitar
185,film,chess-board,bed,surveyor
601,elephant,guitar,fungus,film
16,pants,stomach,clock,gemstone
67,kaleidoscope,pendulum,set,woman
36,brain,printer,pocket,school
16,pants,stomach,clock,gemstone
105,finger,desk,mosquito,finger
118,pants,stomach,clock,gemstone
363,salt,window,pith,solid
Bucket[73]
7,brain,printer,pocket,school
21,skeleton,brain,jet-fighter,apple
261,salt,window,pith,solid
464,woman,sports-car,circle,clown
810,fruit,bowl,rocket,bathroom
910,church,comet,set,worm
980,solid,liquid,pebble,telescope
7,brain,printer,pocket,school
21,skeleton,brain,jet-fighter,apple
50,skeleton,brain,jet-fighter,apple
7,brain,printer,pocket,school
247,slave,paintbrush,button,guitar
287,film,chess-board,bed,surveyor
Bucket[74]
24,tiger,brain,win,chess-board
275,milk,dog,bed,bathtub
333,boss,gemstone,pith,vacuum
370,rocket,oodle,roof,worm
377,hat,film,aeroplane,gas
422,triangle,microscope,record,cave
443,dress,car-race,gate,guitar
452,hat,sandpaper,rocket,signature
530,space,treadmill,software,child
695,foot,sunglasses,hieroglyph,treadmill
713,pith,highway,magnet,printer
850,pepper,kaleidoscope,star,dingbat
878,horse,desk,eraser,sunglasses
24,tiger,brain,win,chess-board
69,yellow,typewriter,mosquito,meat
145,pebble,backpack,car,fire
148,ice,oodle,aeroplane,junk
377,milk,dog,bed,bathtub
Bucket[75]
40,yellow,typewriter,mosquito,meat
46,ice,oodle,aeroplane,junk
95,torch,shop,fork,ring
146,eyes,highway,pebble,kaleidoscope
349,pocket,bottle,freeway,family
372,magnet,necklace,diamond,treadmill
528,x-ray,kitchen,post,fruit
533,chief,guitar,hose,tunnel
644,carpet,videotape,coffee-shop,tongue
769,sandwich,pendulum,rock,sunglasses
906,coffee,sunglasses,hose,comet
923,monster,festival,arm,car-race
40,yellow,typewriter,mosquito,meat
46,ice,oodle,aeroplane,junk
95,torch,shop,fork,ring
75,ice,oodle,aeroplane,junk
126,tiger,brain,win,chess-board
248,eyes,highway,pebble,kaleidoscope
Bucket[76]
27,map,water,software,vacuum
37,necklace,hot,cat,weapon
61,slave,freeway,x-ray,tunnel
91,tennis,aeroplane,coffee-shop,dog
121,videotape,bed,post,bee
138,garden,insect,electricity,chisel
386,film,chair,circus,elephant
444,cup,clock,airforce,window
542,cup,bed,swim,junk
594,slave,pith,pocket,database
758,passport,post,hot,apple
27,map,water,software,vacuum
37,necklace,hot,cat,weapon
61,slave,freeway,x-ray,tunnel
91,tennis,aeroplane,coffee-shop,dog
56,map,water,software,vacuum
78,slave,bed,barbecue,signature
121,double,coffee,leather,snail
139,necklace,hot,cat,weapon
151,slave,bed,barbecue,signature
302,garden,mum,hat,desk
370,meteor,sphere,button,dingbat
Bucket[77]
10,shoes,rifle,drum,bowl
246,stomach,arm,sword,chess-board
523,fruit,plane,airforce,zoo
580,apple,aeroplane,electricity,desk
720,web,software,leather,oodle
725,weapon,roof,pebble,bird
866,torpedo,gasp,spectrum,surveyor
10,shoes,rifle,drum,bowl
10,shoes,rifle,drum,bowl
112,shoes,rifle,drum,bowl
193,tennis,aeroplane,coffee-shop,dog
194,double,coffee,leather,snail
240,garden,insect,electricity,chisel
346,solid,win,mum,album
